# docker compose up --force-recreate --build
services:
    app:
        build:
            context: docker/8.3
        volumes:
            - $PWD/:/app
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        command: docker-app-start
